# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1ccdb615b90c04ed8d33f3e62db4c155774a19a9686264d860db196ed1394a45900fb2955730bef94db9c6c7e8b09464f225c4c9b154210ea96c7029f2af9010

test:
  secret_key_base: e5678a2a0a9d8ddc11d354ba414c1671f146116162e85ee4f71bdf230f0cd119eafaf89d9cf900953e74a1a3cd394453804badd938496b611d9379cf87a76814

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
